### ISSUE TITLE
Call to .signMessage and .signMessageRaw silently fail before the timeout error occurs

### ISSUE THREAD

**Issue by Schwartz10** [ChainSafe/filsnap#130]
1. Call FilecoinSnapApi.signMessage or .signMessageRaw
2. Wait about 30-45 seconds
3. Reject transaction (or accept)
4. No response (or error) comes back from call in step 1
5. About 20 seconds later (depending on how long you waited in step 2), the `Request timed out` error gets thrown

Ideally the request timed out error should occur when the request actually times out, so we don't have this long period of waiting for errors to propagate

**Comment by mpetrunic** [comment]
I wonder if this is actually related to Metamask itself rather than snap as I don't think we throw timeout error anywhere. cc @rekmarks

**Comment by mpetrunic** [comment]
Closed in favour of https://github.com/MetaMask/snaps-skunkworks/issues/380 as this is Metamask issue not snap itself.
