### ISSUE TITLE
[bug]: Fields with falsey values do not show up in Signing UI

### ISSUE THREAD

**Issue by Schwartz10** [ChainSafe/filsnap#148]
### Describe the bug

Let's say I want to send some FIL (`method: 0`). The FILSnap Signing UI will not show the `Method` arg because the field is falsey. Could we just remove this `filter`? https://github.com/ChainSafe/filsnap/blob/master/packages/snap/src/util/messageCreator.ts#L7

### To Reproduce

Submit a simple TRANSFER - the `method: 0` won't show up in the signing UI

### Relevant log output

```shell
NA
```

### Expected behavior

To show all fields that are being signed, even if they are falsey values

### Additional context

NA

**Comment by BeroBurny** [comment]
ups
