### ISSUE TITLE
[bug]: snap does not connect to UI and incorrectly says the installation prompt has not been accepted

### ISSUE THREAD

**Issue by danforbes** [ChainSafe/filsnap#218]
### Describe the bug

After installing the snap, I'm still not able to interact with the UI because it seems that the snap is crashing and the UI continues to show the notification that the installation prompt needs to be accepted.

### To Reproduce

1. Install MetaMask Flask
2. Visit the Filsnap showcase and accept the installation prompt

### Relevant log output

```shell
MetaMask - RPC Error: 'fetch' called on an object that does not implement interface Window.
```

### Expected behavior

When I install Filsnap into MetaMask Flask I am able to interact with the Filsnap showcase

### Additional context

I am using Firefox
![image](https://user-images.githubusercontent.com/2193247/182876284-accdc116-c320-42f2-b4ec-065c907c7631.png)

**Comment by CocDap** [comment]
i stuck with same issue (Metamask Flask in FireFox) 
`
MetaMask - RPC Error: The snap "local:http://localhost:8081" is not installed. This is a bug, please report it. 
`

Note: Snap is installed

**Comment by kunal-iitj** [comment]
Did you find any solution to this

**Comment by CocDap** [comment]
@kunal-gg , please change to Chrome extension. There are some issues when you using Firefox Addon

**Comment by BeroBurny** [comment]
Just checked in seems that work on firefox and chrome with version `10.24.2` (current)

thin this issues is been connected with bug on MetaMask https://github.com/MetaMask/metamask-extension/issues/16176

**Comment by adysrecovery** [comment]
Same issue for me.

Metamask: 10.25.0-flask.0
Chrome Version: 110.0.5481.178 (Official Build) (64-bit)
Windows 10

https://filsnap.chainsafe.io/ 
Keep saying: "Please accept Snap installation prompt"

**Comment by montera82** [comment]
this issue is still there why wasit closed?

**Comment by BeroBurny** [comment]
it is a new issue related to the release of MetaMask 10.25
https://github.com/MetaMask/snaps-monorepo/discussions/1198

Sometimes breaking changes can break same thing multiple times
