### ISSUE TITLE
Demo not work

### ISSUE THREAD

**Issue by badkk** [ChainSafe/filsnap#80]
I clone the proj, install the beta-metamask. Run:
1. `yarn`
2. `yarn demo`
3. `yarn global add snap-cli`

but with the following error:

![image](https://user-images.githubusercontent.com/10335300/118941400-433fac00-b984-11eb-806c-71a0e4e536e6.png)

**Comment by zikunfan** [comment]
I was wondering if that because of the wrong version of `snap-cli`? My snap-cli version is `0.4.1`

**Comment by MakMuftic** [comment]
Hi, I cloned a fresh instance of repo and then run `yarn` followed by `yarn start demo` - and everything seems to be working properly. 

I think that your `snap-cli` version is actual problem - we had to use our fork of `snap-cli` to successfully implement all functionalities, so in this repo we are using `@nodefactory/snaps-cli` (**version 1.5.0**).

**Comment by piotr-roslaniec** [comment]
@MakMuftic Could you share more about prerequisites to run the demo? I've tried running it with different versions of `metamask-snaps-beta` but I always arrive at issue with `RPC Error: Plugin RPC message handler not found.`

**Comment by longfeiWan9** [comment]
@zikunfan @piotr-roslaniec any luck of running this demo with 9.3.0 beta ?
