### ISSUE TITLE
Request - adapter - export `isSnapInstalled` and `MetamaskFilecoinSnap`

### ISSUE THREAD

**Issue by Schwartz10** [ChainSafe/filsnap#91]
A developer like myself likes to have maximum control over the function calls to show the right UI given the user's MetaMask state (and version). 

I'd love to have all the utility helper functions exported https://github.com/ChainSafe/filsnap/blob/master/packages/adapter/src/index.ts#L10, so i can basically rewrite `enableFilecoinSnap` myself. Currently `isSnapInstalled` is the only utility not exported.

Another question - how in the future will `isSnapInstalled` handle minor, non-breaking version updates to the snap?

**Comment by mpetrunic** [comment]
Just to clarify, you just wan't for us to add `isSnapInstalled` exported?

> Another question - how in the future will isSnapInstalled handle minor, non-breaking version updates to the snap?
Seems like Metamask exposes snap `version` here: https://github.com/ChainSafe/filsnap/blob/12fe6ea84c8b9c704ed104ce054425f779a704ee/packages/adapter/src/utils.ts#L11
so we can check version when checking if snap is installed

**Comment by Schwartz10** [comment]
> Just to clarify, you just wan't for us to add isSnapInstalled exported?

Yes please! 

> so we can check version when checking if snap is installed

Wondering moreso about the `snapOrigin` argument for `isSnapInstalled` - https://github.com/ChainSafe/filsnap/blob/master/packages/adapter/src/index.ts#L5

Does this IPFS hash change on each version upgrade?
