### ISSUE TITLE
Warning - gas estimation technique could result in high fees

### ISSUE THREAD

**Issue by Schwartz10** [ChainSafe/filsnap#94]
This _probably_ won't happen because regular transfers are normally a pretty cheap operation, but there's no ceiling gas amount in FILSnap's gas estimation techniques. 

Here's how we do it in the glif wallet modules https://github.com/glifio/modules/blob/refactor/packages/filecoin-wallet-provider/src/filecoin.ts#L165 - note, you can use this package on npm too if you'd like. `@glif/filecoin-wallet-provider`

**Comment by mpetrunic** [comment]
In the snap, gas estimation is left to the dapp as snap signs given the message it doesn't modify it before signing. We could expose message that provides dapp with estimation.

**Comment by Schwartz10** [comment]
I'm referring to this https://github.com/ChainSafe/filsnap/blob/master/packages/snap/src/rpc/signMessage.ts#L28-L34
