### ISSUE TITLE
Timeout error occurs when transaction signature has been sitting too long

### ISSUE THREAD

**Issue by Schwartz10** [ChainSafe/filsnap#97]
1. Invoke a signature request 
2. Wait a long time
3. Sign it

Request "times out"

**Comment by BeroBurny** [comment]
Currently is not possible to fix this as-is implementation issue on snap, will be left open as a reminder to fix it when will be possible

**Comment by mpetrunic** [comment]
duplicate of https://github.com/ChainSafe/filsnap/issues/130
